export enum Actions {
    SAVE_VALUE = "MARKET_CAP_PERCENTAGE_24H",
    LOAD_COIN = "LOAD_COIN",
    LOAD_USER = "LOAD_USER",
    LOAD_WATCHLIST = "LOAD_WATCHLIST",
    ADD_COIN_TO_WATCHLIST = 'ADD_COIN_TO_WATCHLIST',
    REMOVE_COIN_FROM_WATCHLIST = 'REMOVE_COIN_FROM_WATCHLIST',
    LOAD_PORTFOLIO = "LOAD_PORTFOLIO",
    ADD_COIN_TO_PORTFOLIO = 'ADD_COIN_TO_PORTFOLIO',
    REMOVE_COIN_FROM_PORTFOLIO = 'REMOVE_COIN_FROM_PORTFOLIO'
}